# Generated by Django 2.2.7 on 2019-11-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='top',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usa', models.IntegerField()),
                ('kor', models.IntegerField()),
                ('chn', models.IntegerField()),
                ('jpn', models.IntegerField()),
                ('deu', models.IntegerField()),
                ('fra', models.IntegerField()),
                ('gbr', models.IntegerField()),
                ('ita', models.IntegerField()),
            ],
        ),
    ]
